// <auto-generated />
using System;
using ListOfHotels_Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListOfHotels_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727161105_AddLocationEntityAndSeedDataForCitiesAndHotels")]
    partial class AddLocationEntityAndSeedDataForCitiesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListOfHotels_Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tabriz",
                            ShortName = "TBZ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shiraz",
                            ShortName = "SHZ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Esfahan",
                            ShortName = "EFN"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kish",
                            ShortName = "KSH"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hamedan",
                            ShortName = "HMN"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mashhad",
                            ShortName = "MSH"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gilan",
                            ShortName = "GLN"
                        });
                });

            modelBuilder.Entity("ListOfHotels_Core.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "هتل اهراب",
                            Stars = 3
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Shahriyar",
                            Stars = 5
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Pars",
                            Stars = 4
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Negin",
                            Stars = 3
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Golha",
                            Stars = 4
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Yas",
                            Stars = 3
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Name = "Azadi",
                            Stars = 4
                        },
                        new
                        {
                            Id = 8,
                            CityId = 7,
                            Name = "Gisu",
                            Stars = 4
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Name = "PolDokhtar",
                            Stars = 5
                        },
                        new
                        {
                            Id = 10,
                            CityId = 2,
                            Name = "Hafez",
                            Stars = 5
                        },
                        new
                        {
                            Id = 11,
                            CityId = 5,
                            Name = "Hegmatane",
                            Stars = 5
                        },
                        new
                        {
                            Id = 12,
                            CityId = 3,
                            Name = "ChehelSotun",
                            Stars = 5
                        });
                });

            modelBuilder.Entity("ListOfHotels_Core.Entities.Hotel", b =>
                {
                    b.HasOne("ListOfHotels_Core.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ListOfHotels_Core.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");

                            b1.HasData(
                                new
                                {
                                    HotelId = 1,
                                    Address = "خیابان اهراب",
                                    City = "تبریز",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 2,
                                    Address = "خیابان شهریار",
                                    City = "تبریز",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 3,
                                    Address = "خیابان شاه گلی",
                                    City = "تبریز",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 4,
                                    Address = "خیابان نگین کیش",
                                    City = "کیش",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 5,
                                    Address = "خیابان گلهای شیرازی",
                                    City = "شیراز",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 6,
                                    Address = "خیابان یاسمن",
                                    City = "مشهد",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 7,
                                    Address = "خیابان آزادی",
                                    City = "کیش",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 8,
                                    Address = "خیابان گیلکان",
                                    City = "گیلان",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 9,
                                    Address = "خیابان پل دختر",
                                    City = "اصفهان",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 10,
                                    Address = "خیابان حافظ شیرازی",
                                    City = "شیراز",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 11,
                                    Address = "خیابان هگمتانه",
                                    City = "همدان",
                                    Country = "ایران"
                                },
                                new
                                {
                                    HotelId = 12,
                                    Address = "خیابان چهل ستون",
                                    City = "اصفهان",
                                    Country = "ایران"
                                });
                        });

                    b.Navigation("City");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ListOfHotels_Core.Entities.City", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
